services:
  db:
    image: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./envs/.dev.env
    ports:
      - '5432:5432'

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/blogapp
    ports:
      - "8000:8000"
    env_file:
      - envs/.dev.env
    depends_on:
      - db
volumes:
  dbdata:
