# Generated by Django 4.2.7 on 2023-11-08 00:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assembled_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cod_serie', models.CharField(default='00000000000000', max_length=14)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='app.cliente')),
            ],
            options={
                'verbose_name_plural': 'Equipamento',
            },
        ),
    ]
