# Generated by Django 4.2.7 on 2023-11-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0004_equipamento_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipamento',
            options={'verbose_name_plural': 'Equipamentos'},
        ),
    ]
