# Generated by Django 4.2.7 on 2023-11-17 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_frota_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='frota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frota', to='frota.frota'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='processo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processo', to='frota.processo'),
        ),
    ]
